version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file frontend.yaml --s3-bucket cloudformation-lexlambda-ansh --output-template-file output.yaml
      - ls
    build:
      - aws s3 sync ./frontend/ "s3://smartphotoalbumui2-ansh"

artifacts:
  type: zip
  files:
    - frontend.yaml
    - output.yaml
    - packaged-template.json
