version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file frontend.yaml --s3-bucket lambda-cloudformation-rv --output-template-file output.yaml
artifacts:
  type: zip
  files:
    - frontend.yaml
    - output.yaml
