AWSTemplateFormatVersion: 2010-09-09
Transform: "AWS::Serverless-2016-10-31"
Description: Cloud formation for frontend

Resources:
# Front-end bucket
  S3BUCKET1:
    Type: 'AWS::S3::Bucket'
    Properties:
        BucketName: smartphotoalbumui2-ansh
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html

# Photos buckets
  S3BUCKET2:
    Type: 'AWS::S3::Bucket'
    Properties: 
        BucketName: storephotos-ansh
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
